# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_tensor.ipynb.

# %% auto 0
__all__ = ['Tensor', 'AddTensor', 'MulTensor', 'MmulTensor', 'SumTensor']

# %% ../nbs/00_tensor.ipynb 4
class Tensor:
    op = "L"
    name: str = ""
    parents: list = []

    def __init__(self, data, name=""):
        self.data = data
        self.name = name
        self.grad = np.zeros_like(self.data)

    def add(self, other, name):
        out = AddTensor(data=self.data + other.data, name=name)
        out.parents = [self, other]
        return out

    def mul(self, other, name):
        out = MulTensor(data=self.data * other.data, name=name)
        out.parents = [self, other]
        return out

    def mmul(self, other, name):
        out = MulTensor(data=self.data @ other.data, name=name)
        out.parents = [self, other]
        return out

    def sum(self, name):
        out = SumTensor(data=self.data.sum(), name=name)
        out.parents = [self]
        return out

    def backward(self):
        # Create a list of all parent nodes, in reverse order
        # Start with the current node
        visited = []
        nodes = []

        def walk(node):
            for p in node.parents:
                if p not in visited:
                    visited.append(p)
                    walk(p)
                    nodes.append(p)

        walk(self)
        nodes.append(self)

        # print(nodes)
        self.grad = np.ones_like(self.data)
        for n in nodes[::-1]:
            if hasattr(n, "_backward"):
                n._backward()

    def __repr__(self):
        res = f"[{self.op or ''}] {self.name}={str(self.data)} {self.name}.grad={str(self.grad)}"
        if self.parents:
            res += (
                f" {self.name}.parents=["
                + ",".join([p.name for p in self.parents])
                + "]"
            )

        return f"Tensor({res})"


class AddTensor(Tensor):
    op = "+"

    def _backward(self):
        self.parents[0].grad += self.grad
        self.parents[1].grad += self.grad


class MulTensor(Tensor):
    op = "*"

    def _backward(self):
        self.parents[0].grad += self.grad * self.parents[1].data
        self.parents[1].grad += self.grad * self.parents[0].data


class MmulTensor(Tensor):
    op = "@"

    def _backward(self):
        self.parents[0].grad += self.grad @ self.parents[1].data
        self.parents[1].grad += self.grad @ self.parents[0].data


class SumTensor(Tensor):
    op = "sum"

    def _backward(self):
        self.parents[0].grad += self.grad
