# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_ops.conv.ipynb.

# %% auto 0
__all__ = ['Pad']

# %% ../../nbs/02_ops.conv.ipynb 3
import os

import numpy as np
from tidygrad.ops import (
    UnaryElementwiseOp,
    BaseOp,
)

# %% ../../nbs/02_ops.conv.ipynb 4
from typing import Union, Tuple

# %% ../../nbs/02_ops.conv.ipynb 7
class Pad(UnaryElementwiseOp):
    """Pad a tensor"""

    name_template = "pad2d({})"

    def __init__(self, a, padding: Union[int, Tuple[int, int]], name=None):
        super().__init__(a, name=name)
        self.padding = (padding, padding) if isinstance(padding, int) else padding
        self.set_out(np_pad2d(a.data, self.padding))

    def backward(self):
        self.parents[0].grad += np_unpad2d(self.out.grad, self.padding)
        # pY, pX = self.padding
        # slices = (slice(None),) * (len(self.args[0].shape) - 2) \
        #     + (slice(pY, -pY),) + (slice(pX, -pX),)
        # self.parents[0].grad += self.out.grad[slices]
