# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_ops_loss.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/02_ops_loss.ipynb 2
import os

import numpy as np

# from tidygrad.tensor import Tensor
# from tidygrad.ops import ExpLog
# from tidygrad.func import softmax

# class Tensor:
#     ...

# %% ../../nbs/02_ops_loss.ipynb 3
# | export
